### ISSUE TITLE
Command not found Error

### ISSUE THREAD

**Issue by neelabhsinha** [rutvora/PS_Helper#1]
After cloning the repo and executing, moving in the cloned repo folder, gives the following error - 

bash: scraper.exe: command not found
bash: scraper: command not found

**Comment by YashxD** [comment]
To execute binaries not stored in directories in your PATH variable, you need to specify the location of that binary.
For example, if you're in the master root directory, the command should be 
./scraper -g ______
and not 
scraper -g ______

**Comment by rutvora** [comment]
@YashxD is correct
